site_name: Introducción a los retos capture the flag (CTF)

theme:
  name: material
  locale: es
  language: es
  features:
    - navigation.tabs
    - navigation.tracking
  logo: images/logo.jpg
  favicon: images/logo.jpg

nav:
  - "Inicio": index.md
  - "Redes":
      - Inicio: redes/index.md
      - Herramientas: redes/tools.md
      - Retos: redes/retos.md
  - Web:
      - Inicio: web/index.md
      - Herramientas: web/tools.md
  - Forense:
      - Inicio: forense/index.md
      - Herramientas: forense/tools.md
      - Retos: forense/retos.md
  - Stego:
      - Inicio: stego/index.md
      - Herramientas: stego/tools.md
      - Retos: stego/retos.md
  - Crypto:
      - Inicio: crypto/index.md
      - Herramientas: crypto/tools.md
      - Retos: crypto/retos.md
