site_name: Introducción a los retos capture the flag (CTF)

theme:
  name: material
locale: es

nav:
  - "Inicio": index.md
  - "Redes":
      - Inicio: redes/index.md
      - Herramientas: redes/tools.md
  - Web:
      - Inicio: web/index.md
      - Herramientas: web/tools.md
  - Forense:
      - Inicio: forense/index.md
      - Herramientas: forense/tools.md
      - Retos: forense/retos.md
  - Stego:
      - Inicio: stego/index.md
      - Herramientas: stego/tools.md
      - Retos: stego/retos.md
